# Generated by Django 5.2.8 on 2025-12-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebok_link',
            new_name='facebook_link',
        ),
    ]
