# Generated by Django 5.2.8 on 2025-11-29 17:48
from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=CKEditor5Field(),
        ),
    ]
